import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { NextProvider as NextUIProvider } from "./providers";
import "./globals.css";
import { AuthContextProvider } from "@/hooks/useAuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body className={`min-h-[100vh] ${inter.className}`}>
                <NextUIProvider>
                    <AuthContextProvider>{children}</AuthContextProvider>
                </NextUIProvider>
            </body>
        </html>
    );
}
