import type { Metadata } from "next";
import { Inter, Teko } from "next/font/google";
import { Toaster } from "sonner";

import { NextProvider as NextUIProvider, SWRConfigProvider } from "./providers";
import "./globals.css";
import { AuthContextProvider } from "@/hooks/useAuthContext";

const inter = Inter({ subsets: ["latin"] });
const teko = Teko({ subsets: ["latin"], variable: "--font-teko" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body
                className={`min-h-[100vh] ${teko.variable}  ${inter.className}`}
            >
                <NextUIProvider>
                    <AuthContextProvider>
                        <SWRConfigProvider>
                            {children}
                            <Toaster />
                        </SWRConfigProvider>
                    </AuthContextProvider>
                </NextUIProvider>
            </body>
        </html>
    );
}
